name: mzsearch_env
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - r-base=4.3
  - r-optparse=1.7.5
  - bioconductor-MSnbase=2.28.1
  - python=3.12.4
  - matplotlib=3.8.4
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.13.1
